version: '3.8'

services:
  neos:
    build:
       context: .
       dockerfile: ./docker/Dockerfile
    environment:
      FLOW_CONTEXT: 'Development/Docker'
      #FLOW_CONTEXT: 'Production'
      COMPOSER_CACHE_DIR: '/composer_cache'
      # DB connection
      DB_NEOS_HOST: 'db'
      DB_NEOS_PORT: 3306
      DB_NEOS_PASSWORD: 'neos'
      DB_NEOS_USER: 'neos'
      DB_NEOS_DATABASE: 'neos'
      # Neos
      ADMIN_USERNAME: 'admin'
      ADMIN_PASSWORD: 'password'
    volumes:
      - ./composer.json:/app/composer.json:cached
      - ./composer.lock:/app/composer.lock:cached
      # Code
      - ./DistributionPackages:/app/DistributionPackages:cached
      - ./Packages:/app/Packages:delegated
      - ./Configuration:/app/Configuration:cached
      # Logs
      - ./Data/Persistent:/app/Data/Persistent/:delegated
      # Media for persistence
      - ./Data/Logs:/app/Data/Logs/:delegated
      - ./setup-neos.sh:/app/setup-neos.sh
    ports:
      - '8081:8081'
      - '8082:8082'
    networks:
      - neosdevelopment
    depends_on:
      - db

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: neos
      MYSQL_DATABASE: neos
      MYSQL_USER: neos
      MYSQL_PASSWORD: neos
    volumes:
      - db:/var/lib/mysql
    ports:
      - '13306:3306'
    networks:
      - neosdevelopment

  adminer:
    image: wodby/adminer:4.7
    depends_on:
      - "db"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: neos
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 7000:9000
    networks:
      - neosdevelopment

volumes:
  db:

networks:
  neosdevelopment:
    name: neosdevelopment
